package com.example.nallanudiapp


val wordDatabase: List<Word> = listOf(


    Word(english="Noun", kannada="ನಾಮಪದ", meaning="Name of person/place/thing", subject="English"),
Word(english="Verb", kannada="ಕ್ರಿಯಾಪದ", meaning="Action word", subject="English"),
Word(english="Adjective", kannada="ವಿಶೇಷಣ", meaning="Describes noun", subject="English"),
Word(english="Adverb", kannada="ಕ್ರಿಯಾವಿಶೇಷಣ", meaning="Describes verb", subject="English"),
Word(english="Pronoun", kannada="ಸರ್ವನಾಮ", meaning="Replaces noun", subject="English"),
Word(english="Tense", kannada="ಕಾಲ", meaning="Time of action", subject="English"),
Word(english="Sentence", kannada="ವಾಕ್ಯ", meaning="Complete thought", subject="English"),
Word(english="Phrase", kannada="ವಾಕ್ಯಾಂಶ", meaning="Group of words", subject="English"),
Word(english="Clause", kannada="ಉಪವಾಕ್ಯ", meaning="Part of sentence", subject="English"),
Word(english="Grammar", kannada="ವ್ಯಾಕರಣ", meaning="Language rules", subject="English"),
Word(english="Vocabulary", kannada="ಪದಸಂಪತ್ತು", meaning="Word knowledge", subject="English"),
Word(english="Reading", kannada="ಓದು", meaning="Understanding text", subject="English"),
Word(english="Writing", kannada="ಬರಹ", meaning="Express ideas", subject="English"),
Word(english="Listening", kannada="ಕೇಳುವುದು", meaning="Understand speech", subject="English"),
Word(english="Speaking", kannada="ಮಾತನಾಡುವುದು", meaning="Communication", subject="English"),
Word(english="Story", kannada="ಕಥೆ", meaning="Narrative text", subject="English"),
Word(english="Poem", kannada="ಕವನ", meaning="Poetry writing", subject="English"),
Word(english="Author", kannada="ಲೇಖಕ", meaning="Writer", subject="English"),
Word(english="Title", kannada="ಶೀರ್ಷಿಕೆ", meaning="Heading", subject="English"),
Word(english="Character", kannada="ಪಾತ್ರ", meaning="Person in story", subject="English"),
Word(english="Dialogue", kannada="ಸಂಭಾಷಣೆ", meaning="Conversation", subject="English"),
Word(english="Plot", kannada="ಕಥಾವಸ್ತು", meaning="Story structure", subject="English"),
Word(english="Theme", kannada="ಥೀಮ್", meaning="Central idea", subject="English"),
Word(english="Spelling", kannada="ಅಕ್ಷರಲಿಪಿ", meaning="Correct writing", subject="English"),
Word(english="Punctuation", kannada="ವಿರಾಮಚಿಹ್ನೆ", meaning="Marks in writing", subject="English"),
Word(english="Capital", kannada="ಮೂಲಾಕ್ಷರ", meaning="Uppercase letter", subject="English"),
Word(english="Lowercase", kannada="ಸಣ್ಣಅಕ್ಷರ", meaning="Small letters", subject="English"),
Word(english="Formal", kannada="ಔಪಚಾರಿಕ", meaning="Official style", subject="English"),
Word(english="Informal", kannada="ಅನೌಪಚಾರಿಕ", meaning="Casual style", subject="English"),
Word(english="Email", kannada="ಇಮೇಲ್", meaning="Electronic message", subject="English"),
Word(english="Letter", kannada="ಪತ್ರ", meaning="Written message", subject="English"),
Word(english="Summary", kannada="ಸಾರಾಂಶ", meaning="Short version", subject="English"),
Word(english="Introduction", kannada="ಪರಿಚಯ", meaning="Beginning", subject="English"),
Word(english="Conclusion", kannada="ನಿರ್ಣಯ", meaning="Ending", subject="English"),
Word(english="Draft", kannada="ಕರಡು", meaning="Initial writing", subject="English"),
Word(english="Edit", kannada="ಸಂಪಾದನೆ", meaning="Improve text", subject="English"),
Word(english="Proofread", kannada="ಪರಿಶೀಲನೆ", meaning="Check mistakes", subject="English"),
Word(english="Speech", kannada="ಭಾಷಣ", meaning="Public talk", subject="English"),
Word(english="Debate", kannada="ಚರ್ಚೆ", meaning="Discussion", subject="English"),
Word(english="Note", kannada="ಟಿಪ್ಪಣಿ", meaning="Short record", subject="English"),
Word(english="Report", kannada="ವರದಿ", meaning="Detailed writing", subject="English"),
Word(english="Article", kannada="ಲೇಖನ", meaning="Informative writing", subject="English"),
Word(english="Blog", kannada="ಬ್ಲಾಗ್", meaning="Online writing", subject="English"),
Word(english="Review", kannada="ವಿಮರ್ಶೆ", meaning="Opinion writing", subject="English"),
Word(english="Fiction", kannada="ಕಲ್ಪಿತ", meaning="Imaginary writing", subject="English"),
Word(english="Nonfiction", kannada="ನಿಜವಾದ", meaning="Real writing", subject="English"),
Word(english="Editor", kannada="ಸಂಪಾದಕ", meaning="Text reviewer", subject="English"),
Word(english="Publisher", kannada="ಪ್ರಕಾಶಕ", meaning="Prints books", subject="English"),
Word(english="Dictionary", kannada="ನಿಘಂಟು", meaning="Word meanings", subject="English"),
Word(english="Synonym", kannada="ಸಮಾನಾರ್ಥಕ", meaning="Same meaning", subject="English"),
Word(english="Antonym", kannada="ವಿರುದ್ಧಾರ್ಥಕ", meaning="Opposite meaning", subject="English"),
Word(english="Idiom", kannada="ವಾಕ್ಯಪ್ರಯೋಗ", meaning="Special phrase", subject="English"),
Word(english="Simile", kannada="ಉಪಮೆ", meaning="Comparison using like", subject="English"),
Word(english="Metaphor", kannada="ರೂಪಕ", meaning="Indirect comparison", subject="English"),
Word(english="Voice", kannada="ಧ್ವನಿ", meaning="Active or passive", subject="English"),
Word(english="Preposition", kannada="ಪೂರ್ವಪ್ರತ್ಯಯ", meaning="Shows relation", subject="English"),
Word(english="Conjunction", kannada="ಸಂಯೋಜಕ", meaning="Joins words", subject="English"),
Word(english="Interjection", kannada="ಉದ್ಗಾರ", meaning="Express emotion", subject="English"),
Word(english="Alphabet", kannada="ವರ್ಣಮಾಲೆ", meaning="Set of letters", subject="English"),


        // ===== MATHS =====
        Word (english="Addition", kannada="ಜೋಡಣೆ", meaning="Sum of numbers", subject="Math"),
Word(english="Subtraction", kannada="ಕಳೆದಿಕೆ", meaning="Finding difference", subject="Math"),
Word(english="Multiplication", kannada="ಗುಣಾಕಾರ", meaning="Repeated addition", subject="Math"),
Word(english="Division", kannada="ಭಾಗಾಕಾರ", meaning="Splitting equally", subject="Math"),
Word(english="Number", kannada="ಸಂಖ್ಯೆ", meaning="Mathematical value", subject="Math"),
Word(english="Integer", kannada="ಪೂರ್ಣಾಂಕ", meaning="Whole number", subject="Math"),
Word(english="Fraction", kannada="ಭಿನ್ನರಾಶಿ", meaning="Part of whole", subject="Math"),
Word(english="Decimal", kannada="ದಶಮಾಂಶ", meaning="Fraction in decimal form", subject="Math"),
Word(english="Percentage", kannada="ಶೇಕಡಾವಾರು", meaning="Per hundred", subject="Math"),
Word(english="Ratio", kannada="ಅನುಪಾತ", meaning="Comparison of quantities", subject="Math"),
Word(english="Proportion", kannada="ಸಮಾನಾನುಪಾತ", meaning="Equal ratios", subject="Math"),
Word(english="Algebra", kannada="ಬೀಜಗಣಿತ", meaning="Math with variables", subject="Math"),
Word(english="Variable", kannada="ಚರ", meaning="Unknown value", subject="Math"),
Word(english="Constant", kannada="ಸ್ಥಿರ", meaning="Fixed value", subject="Math"),
Word(english="Equation", kannada="ಸಮೀಕರಣ", meaning="Math statement", subject="Math"),
Word(english="Expression", kannada="ಪ್ರಕಟನೆ", meaning="Combination of terms", subject="Math"),
Word(english="Term", kannada="ಪದ", meaning="Single math part", subject="Math"),
Word(english="Coefficient", kannada="ಗುಣಾಂಕ", meaning="Number before variable", subject="Math"),
Word(english="Exponent", kannada="ಘಾತ", meaning="Power of number", subject="Math"),
Word(english="Square", kannada="ವರ್ಗ", meaning="Number multiplied by itself", subject="Math"),
Word(english="Cube", kannada="ಘನ", meaning="Number multiplied thrice", subject="Math"),
Word(english="Root", kannada="ಮೂಲ", meaning="Inverse of power", subject="Math"),
Word(english="Square root", kannada="ವರ್ಗಮೂಲ", meaning="Root of square", subject="Math"),
Word(english="Graph", kannada="ಗ್ರಾಫ್", meaning="Visual representation", subject="Math"),
Word(english="Axis", kannada="ಅಕ್ಷ", meaning="Graph line", subject="Math"),
Word(english="Coordinate", kannada="ಸಂಯೋಜಕ", meaning="Point location", subject="Math"),
Word(english="Line", kannada="ರೇಖೆ", meaning="Straight path", subject="Math"),
Word(english="Angle", kannada="ಕೋನ", meaning="Two lines meeting", subject="Math"),
Word(english="Triangle", kannada="ತ್ರಿಭುಜ", meaning="3 sided shape", subject="Math"),
Word(english="Square shape", kannada="ಚೌಕ", meaning="4 equal sides", subject="Math"),
Word(english="Rectangle", kannada="ಆಯತ", meaning="Opposite sides equal", subject="Math"),
Word(english="Circle", kannada="ವೃತ್ತ", meaning="Round shape", subject="Math"),
Word(english="Radius", kannada="ಅರ್ಧವ್ಯಾಸ", meaning="Center to edge", subject="Math"),
Word(english="Diameter", kannada="ವ್ಯಾಸ", meaning="Across circle", subject="Math"),
Word(english="Perimeter", kannada="ಪರಿಧಿ", meaning="Boundary length", subject="Math"),
Word(english="Area", kannada="ವಿಸ್ತೀರ್ಣ", meaning="Surface size", subject="Math"),
Word(english="Volume", kannada="ಆಯತನ", meaning="Space occupied", subject="Math"),
Word(english="Measurement", kannada="ಅಳತೆ", meaning="Size or quantity", subject="Math"),
Word(english="Unit", kannada="ಘಟಕ", meaning="Standard measure", subject="Math"),
Word(english="Meter", kannada="ಮೀಟರ್", meaning="Length unit", subject="Math"),
Word(english="Kilogram", kannada="ಕಿಲೋಗ್ರಾಂ", meaning="Weight unit", subject="Math"),
Word(english="Second", kannada="ಸೆಕೆಂಡ್", meaning="Time unit", subject="Math"),
Word(english="Data", kannada="ಡೇಟಾ", meaning="Collected values", subject="Math"),
Word(english="Statistics", kannada="ಅಂಕಿಅಂಶ", meaning="Data analysis", subject="Math"),
Word(english="Mean", kannada="ಸರಾಸರಿ", meaning="Average value", subject="Math"),
Word(english="Median", kannada="ಮಧ್ಯಕ", meaning="Middle value", subject="Math"),
Word(english="Mode", kannada="ಅತ್ಯಧಿಕ", meaning="Most frequent", subject="Math"),
Word(english="Probability", kannada="ಸಂಭಾವನೆ", meaning="Chance of event", subject="Math"),
Word(english="Set", kannada="ಸಮೂಹ", meaning="Collection of elements", subject="Math"),
Word(english="Subset", kannada="ಉಪಸಮೂಹ", meaning="Part of set", subject="Math"),
Word(english="Union", kannada="ಸಂಯೋಜನೆ", meaning="Combine sets", subject="Math"),
Word(english="Intersection", kannada="ಸಂಧಿ", meaning="Common elements", subject="Math"),
Word(english="Difference", kannada="ವ್ಯತ್ಯಾಸ", meaning="Remaining elements", subject="Math"),
Word(english="Matrix", kannada="ಮ್ಯಾಟ್ರಿಕ್ಸ್", meaning="Array of numbers", subject="Math"),
Word(english="Vector", kannada="ವೆಕ್ಟರ್", meaning="Magnitude and direction", subject="Math"),
Word(english="Formula", kannada="ಸೂತ್ರ", meaning="Math rule", subject="Math"),
Word(english="Theorem", kannada="ಸಿದ್ಧಾಂತ", meaning="Proven statement", subject="Math"),
Word(english="Proof", kannada="ಸಾಬೀತು", meaning="Verification", subject="Math"),

    // ===== SCIENCE =====

    Word(english="Force", kannada="ಬಲ", meaning="Push or pull", subject="Science"),
    Word(english="Energy", kannada="ಶಕ್ತಿ", meaning="Capacity to do work", subject="Science"),
    Word(english="Work", kannada="ಕೆಲಸ", meaning="Force applied over distance", subject="Science"),
    Word(english="Power", kannada="ಶಕ್ತಿ ಪ್ರಮಾಣ", meaning="Rate of doing work", subject="Science"),
    Word(english="Motion", kannada="ಚಲನೆ", meaning="Change in position", subject="Science"),
    Word(english="Velocity", kannada="ವೇಗ", meaning="Speed with direction", subject="Science"),
    Word(english="Acceleration", kannada="ವೇಗವರ್ಧನೆ", meaning="Change in velocity", subject="Science"),
    Word(english="Mass", kannada="ಭಾರ", meaning="Amount of matter", subject="Science"),
    Word(english="Weight", kannada="ತೂಕ", meaning="Force due to gravity", subject="Science"),
    Word(english="Gravity", kannada="ಗುರುತ್ವಾಕರ್ಷಣ", meaning="Force of attraction", subject="Science"),

    Word(english="Friction", kannada="ಘರ್ಷಣೆ", meaning="Opposes motion", subject="Science"),
    Word(english="Pressure", kannada="ಒತ್ತಡ", meaning="Force per area", subject="Science"),
    Word(english="Density", kannada="ಸಾಂದ್ರತೆ", meaning="Mass per volume", subject="Science"),
    Word(english="Volume", kannada="ಆಯತನ", meaning="Space occupied", subject="Science"),
    Word(english="Temperature", kannada="ತಾಪಮಾನ", meaning="Measure of heat", subject="Science"),
    Word(english="Heat", kannada="ತಾಪ", meaning="Energy transfer", subject="Science"),
    Word(english="Light", kannada="ಬೆಳಕು", meaning="Visible energy", subject="Science"),
    Word(english="Sound", kannada="ಧ್ವನಿ", meaning="Vibration waves", subject="Science"),
    Word(english="Electricity", kannada="ವಿದ್ಯುತ್", meaning="Flow of charge", subject="Science"),
    Word(english="Magnetism", kannada="ಚುಂಬಕತ್ವ", meaning="Magnetic force", subject="Science"),

    Word(english="Atom", kannada="ಅಣು", meaning="Smallest unit", subject="Science"),
    Word(english="Molecule", kannada="ಅಣುಸಮೂಹ", meaning="Group of atoms", subject="Science"),
    Word(english="Element", kannada="ಮೂಲಧಾತು", meaning="Pure substance", subject="Science"),
    Word(english="Compound", kannada="ಸಂಯುಕ್ತ", meaning="Combined elements", subject="Science"),
    Word(english="Mixture", kannada="ಮಿಶ್ರಣ", meaning="Physical combination", subject="Science"),
    Word(english="Reaction", kannada="ಪ್ರತಿಕ್ರಿಯೆ", meaning="Chemical change", subject="Science"),
    Word(english="Acid", kannada="ಅಮ್ಲ", meaning="Sour substance", subject="Science"),
    Word(english="Base", kannada="ಕ್ಷಾರ", meaning="Bitter substance", subject="Science"),
    Word(english="Salt", kannada="ಉಪ್ಪು", meaning="Product of reaction", subject="Science"),
    Word(english="pH", kannada="ಪಿ ಎಚ್", meaning="Acidity scale", subject="Science"),

    Word(english="Cell", kannada="ಕೋಶ", meaning="Basic unit of life", subject="Science"),
    Word(english="Tissue", kannada="ಕಣಜ", meaning="Group of cells", subject="Science"),
    Word(english="Organ", kannada="ಅಂಗ", meaning="Body part", subject="Science"),
    Word(english="System", kannada="ವ್ಯವಸ್ಥೆ", meaning="Group of organs", subject="Science"),
    Word(english="Heart", kannada="ಹೃದಯ", meaning="Pumps blood", subject="Science"),
    Word(english="Brain", kannada="ಮೆದುಳು", meaning="Controls body", subject="Science"),
    Word(english="Lungs", kannada="ಫೆಫಸು", meaning="Breathing organ", subject="Science"),
    Word(english="Blood", kannada="ರಕ್ತ", meaning="Circulating fluid", subject="Science"),
    Word(english="Nerve", kannada="ನರ", meaning="Carries signals", subject="Science"),
    Word(english="Muscle", kannada="ಪೇಶಿ", meaning="Helps movement", subject="Science"),

    Word(english="Plant", kannada="ಸಸ್ಯ", meaning="Living organism", subject="Science"),
    Word(english="Animal", kannada="ಪ್ರಾಣಿ", meaning="Living organism", subject="Science"),
    Word(english="Photosynthesis", kannada="ಪ್ರಕಾಶಸಂಶ್ಲೇಷಣೆ", meaning="Food making process", subject="Science"),
    Word(english="Respiration", kannada="ಉಸಿರಾಟ", meaning="Energy release", subject="Science"),
    Word(english="Digestion", kannada="ಜೀರ್ಣಕ್ರಿಯೆ", meaning="Breakdown of food", subject="Science"),
    Word(english="Excretion", kannada="ವಿಸರ್ಜನೆ", meaning="Removal of waste", subject="Science"),
    Word(english="Reproduction", kannada="ಪ್ರಜನನ", meaning="Produce offspring", subject="Science"),
    Word(english="Growth", kannada="ವೃದ್ಧಿ", meaning="Increase in size", subject="Science"),
    Word(english="Environment", kannada="ಪರಿಸರ", meaning="Surroundings", subject="Science"),
    Word(english="Ecosystem", kannada="ಪರಿಸರ ವ್ಯವಸ್ಥೆ", meaning="Living system", subject="Science"),

    Word(english="Solar system", kannada="ಸೌರಮಂಡಲ", meaning="Sun and planets", subject="Science"),
    Word(english="Planet", kannada="ಗ್ರಹ", meaning="Orbits sun", subject="Science"),
    Word(english="Earth", kannada="ಭೂಮಿ", meaning="Our planet", subject="Science"),
    Word(english="Moon", kannada="ಚಂದ್ರ", meaning="Earth satellite", subject="Science"),
    Word(english="Sun", kannada="ಸೂರ್ಯ", meaning="Star", subject="Science"),
    Word(english="Star", kannada="ನಕ್ಷತ್ರ", meaning="Luminous body", subject="Science"),
    Word(english="Galaxy", kannada="ಆಕಾಶಗಂಗೆ", meaning="Group of stars", subject="Science"),
    Word(english="Universe", kannada="ಬ್ರಹ್ಮಾಂಡ", meaning="All space", subject="Science"),

    // ===== SOCIAL =====

    Word(english="History", kannada="ಇತಿಹಾಸ", meaning="Study of past", subject="Social"),
    Word(english="Geography", kannada="ಭೂಗೋಳಶಾಸ್ತ್ರ", meaning="Study of earth", subject="Social"),
    Word(english="Civics", kannada="ನಾಗರಿಕಶಾಸ್ತ್ರ", meaning="Study of government", subject="Social"),
    Word(english="Economics", kannada="ಅರ್ಥಶಾಸ್ತ್ರ", meaning="Study of money", subject="Social"),
    Word(english="Society", kannada="ಸಮಾಜ", meaning="Group of people", subject="Social"),
    Word(english="Culture", kannada="ಸಂಸ್ಕೃತಿ", meaning="Traditions and values", subject="Social"),
    Word(english="Tradition", kannada="ಪಾರಂಪರ್ಯ", meaning="Passed customs", subject="Social"),
    Word(english="Heritage", kannada="ಪಾರಂಪರಿಕ ಸಂಪತ್ತು", meaning="Cultural legacy", subject="Social"),
    Word(english="Civilization", kannada="ಸಂಸ್ಕೃತಿ", meaning="Advanced society", subject="Social"),
    Word(english="Community", kannada="ಸಮುದಾಯ", meaning="Group living together", subject="Social"),

    Word(english="Population", kannada="ಜನಸಂಖ್ಯೆ", meaning="Number of people", subject="Social"),
    Word(english="Migration", kannada="ಸ್ಥಳಾಂತರ", meaning="Moving places", subject="Social"),
    Word(english="Urban", kannada="ನಗರ", meaning="City area", subject="Social"),
    Word(english="Rural", kannada="ಗ್ರಾಮೀಣ", meaning="Village area", subject="Social"),
    Word(english="Village", kannada="ಹಳ್ಳಿ", meaning="Small settlement", subject="Social"),
    Word(english="City", kannada="ನಗರ", meaning="Large settlement", subject="Social"),
    Word(english="State", kannada="ರಾಜ್ಯ", meaning="Administrative division", subject="Social"),
    Word(english="Country", kannada="ದೇಶ", meaning="Nation", subject="Social"),
    Word(english="Continent", kannada="ಖಂಡ", meaning="Large landmass", subject="Social"),
    Word(english="Map", kannada="ನಕ್ಷೆ", meaning="Representation of area", subject="Social"),

    Word(english="River", kannada="ನದಿ", meaning="Flowing water", subject="Social"),
    Word(english="Mountain", kannada="ಪರ್ವತ", meaning="High landform", subject="Social"),
    Word(english="Plateau", kannada="ಪೀಠಭೂಮಿ", meaning="Flat high land", subject="Social"),
    Word(english="Desert", kannada="ಮರಳುಭೂಮಿ", meaning="Dry region", subject="Social"),
    Word(english="Climate", kannada="ಹವಾಮಾನ", meaning="Weather condition", subject="Social"),
    Word(english="Weather", kannada="ಹವಾಮಾನ", meaning="Daily condition", subject="Social"),
    Word(english="Forest", kannada="ಅರಣ್ಯ", meaning="Dense trees", subject="Social"),
    Word(english="Agriculture", kannada="ಕೃಷಿ", meaning="Farming", subject="Social"),
    Word(english="Industry", kannada="ಉದ್ಯಮ", meaning="Production activity", subject="Social"),
    Word(english="Trade", kannada="ವ್ಯಾಪಾರ", meaning="Buying and selling", subject="Social"),

    Word(english="Government", kannada="ಸರ್ಕಾರ", meaning="Ruling body", subject="Social"),
    Word(english="Democracy", kannada="ಪ್ರಜಾಪ್ರಭುತ್ವ", meaning="Rule by people", subject="Social"),
    Word(english="Election", kannada="ಚುನಾವಣೆ", meaning="Choosing leaders", subject="Social"),
    Word(english="Vote", kannada="ಮತ", meaning="Right to choose", subject="Social"),
    Word(english="Law", kannada="ಕಾನೂನು", meaning="Rules of country", subject="Social"),
    Word(english="Constitution", kannada="ಸಂವಿಧಾನ", meaning="Basic law", subject="Social"),
    Word(english="Rights", kannada="ಹಕ್ಕುಗಳು", meaning="Freedom given", subject="Social"),
    Word(english="Duties", kannada="ಕರ್ತವ್ಯಗಳು", meaning="Responsibilities", subject="Social"),
    Word(english="Justice", kannada="ನ್ಯಾಯ", meaning="Fair treatment", subject="Social"),
    Word(english="Equality", kannada="ಸಮಾನತೆ", meaning="Equal rights", subject="Social"),

    Word(english="Freedom", kannada="ಸ್ವಾತಂತ್ರ್ಯ", meaning="Independence", subject="Social"),
    Word(english="Independence", kannada="ಸ್ವಾತಂತ್ರ್ಯ", meaning="Freedom from rule", subject="Social"),
    Word(english="Colonialism", kannada="ಔಪನಿವೇಶಿಕತೆ", meaning="Foreign rule", subject="Social"),
    Word(english="Revolution", kannada="ಕ್ರಾಂತಿ", meaning="Major change", subject="Social"),
    Word(english="War", kannada="ಯುದ್ಧ", meaning="Conflict", subject="Social"),
    Word(english="Peace", kannada="ಶಾಂತಿ", meaning="No conflict", subject="Social"),
    Word(english="Leader", kannada="ನಾಯಕ", meaning="Guides people", subject="Social"),
    Word(english="Citizen", kannada="ನಾಗರಿಕ", meaning="Member of country", subject="Social"),
    Word(english="Parliament", kannada="ಸಂಸತ್", meaning="Law making body", subject="Social"),
    Word(english="Policy", kannada="ನೀತಿ", meaning="Government plan", subject="Social"),

    Word(english="Resource", kannada="ಸಂಪನ್ಮೂಲ", meaning="Useful material", subject="Social"),
    Word(english="Natural resources", kannada="ಪ್ರಾಕೃತಿಕ ಸಂಪನ್ಮೂಲ", meaning="From nature", subject="Social"),
    Word(english="Minerals", kannada="ಖನಿಜಗಳು", meaning="Earth materials", subject="Social"),
    Word(english="Water", kannada="ನೀರು", meaning="Essential liquid", subject="Social"),
    Word(english="Land", kannada="ಭೂಮಿ", meaning="Surface of earth", subject="Social"),
    Word(english="Transport", kannada="ಸಾರಿಗೆ", meaning="Movement of goods", subject="Social"),
    Word(english="Communication", kannada="ಸಂವಹನ", meaning="Exchange of info", subject="Social"),
    Word(english="Education", kannada="ಶಿಕ್ಷಣ", meaning="Learning process", subject="Social"),
    Word(english="Health", kannada="ಆರೋಗ್ಯ", meaning="Well-being", subject="Social"),
    Word(english="Development", kannada="ಅಭಿವೃದ್ಧಿ", meaning="Growth of society", subject="Social"),

    // ===== COMMERCE =====

    Word(english="Business", kannada="ವ್ಯವಹಾರ", meaning="Activity of trade", subject="Commerce"),
    Word(english="Trade", kannada="ವ್ಯಾಪಾರ", meaning="Buying and selling", subject="Commerce"),
    Word(english="Commerce", kannada="ವಾಣಿಜ್ಯ", meaning="Business activities", subject="Commerce"),
    Word(english="Industry", kannada="ಉದ್ಯಮ", meaning="Production activity", subject="Commerce"),
    Word(english="Service", kannada="ಸೇವೆ", meaning="Non-product activity", subject="Commerce"),
    Word(english="Goods", kannada="ಸರಕುಗಳು", meaning="Physical items", subject="Commerce"),
    Word(english="Consumer", kannada="ಗ್ರಾಹಕ", meaning="Buyer of goods", subject="Commerce"),
    Word(english="Producer", kannada="ಉತ್ಪಾದಕ", meaning="Makes goods", subject="Commerce"),
    Word(english="Market", kannada="ಮಾರುಕಟ್ಟೆ", meaning="Place of trade", subject="Commerce"),
    Word(english="Demand", kannada="ಬೇಡಿಕೆ", meaning="Need for product", subject="Commerce"),

    Word(english="Supply", kannada="ಪೂರೈಕೆ", meaning="Availability of goods", subject="Commerce"),
    Word(english="Price", kannada="ಬೆಲೆ", meaning="Value of product", subject="Commerce"),
    Word(english="Cost", kannada="ವೆಚ್ಚ", meaning="Expense to produce", subject="Commerce"),
    Word(english="Profit", kannada="ಲಾಭ", meaning="Gain from business", subject="Commerce"),
    Word(english="Loss", kannada="ನಷ್ಟ", meaning="Negative profit", subject="Commerce"),
    Word(english="Capital", kannada="ಮೂಲಧನ", meaning="Money invested", subject="Commerce"),
    Word(english="Investment", kannada="ಹೂಡಿಕೆ", meaning="Money used to earn", subject="Commerce"),
    Word(english="Revenue", kannada="ಆದಾಯ", meaning="Income from sales", subject="Commerce"),
    Word(english="Expense", kannada="ಖರ್ಚು", meaning="Money spent", subject="Commerce"),
    Word(english="Budget", kannada="ಬಜೆಟ್", meaning="Plan of income", subject="Commerce"),

    Word(english="Account", kannada="ಖಾತೆ", meaning="Financial record", subject="Commerce"),
    Word(english="Accounting", kannada="ಲೆಕ್ಕಪತ್ರ", meaning="Recording transactions", subject="Commerce"),
    Word(english="Ledger", kannada="ಲೆಡ್ಜರ್", meaning="Account book", subject="Commerce"),
    Word(english="Journal", kannada="ಜರ್ನಲ್", meaning="Daily record", subject="Commerce"),
    Word(english="Balance", kannada="ಶೇಷ", meaning="Remaining amount", subject="Commerce"),
    Word(english="Asset", kannada="ಆಸ್ತಿ", meaning="Owned property", subject="Commerce"),
    Word(english="Liability", kannada="ಬಾಧ್ಯತೆ", meaning="Debt obligation", subject="Commerce"),
    Word(english="Equity", kannada="ಸ್ವಾಮ್ಯ", meaning="Owner share", subject="Commerce"),
    Word(english="Debit", kannada="ಡೆಬಿಟ್", meaning="Left side entry", subject="Commerce"),
    Word(english="Credit", kannada="ಕ್ರೆಡಿಟ್", meaning="Right side entry", subject="Commerce"),

    Word(english="Bank", kannada="ಬ್ಯಾಂಕ್", meaning="Financial institution", subject="Commerce"),
    Word(english="Loan", kannada="ಸಾಲ", meaning="Borrowed money", subject="Commerce"),
    Word(english="Interest", kannada="ಬಡ್ಡಿ", meaning="Charge for loan", subject="Commerce"),
    Word(english="Savings", kannada="ಉಳಿತಾಯ", meaning="Money saved", subject="Commerce"),
    Word(english="Deposit", kannada="ಠೇವಣಿ", meaning="Money kept in bank", subject="Commerce"),
    Word(english="Withdrawal", kannada="ತೆಗೆದುಕೊಳ್ಳುವುದು", meaning="Taking money out", subject="Commerce"),
    Word(english="Cheque", kannada="ಚೆಕ್", meaning="Bank payment slip", subject="Commerce"),
    Word(english="Credit card", kannada="ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್", meaning="Pay later card", subject="Commerce"),
    Word(english="Debit card", kannada="ಡೆಬಿಟ್ ಕಾರ್ಡ್", meaning="Pay from account", subject="Commerce"),
    Word(english="Transaction", kannada="ವಹಿವಾಟು", meaning="Money exchange", subject="Commerce"),

    Word(english="Tax", kannada="ತೆರಿಗೆ", meaning="Government charge", subject="Commerce"),
    Word(english="GST", kannada="ಜಿಎಸ್‌ಟಿ", meaning="Goods service tax", subject="Commerce"),
    Word(english="Invoice", kannada="ರಸೀದಿ", meaning="Bill document", subject="Commerce"),
    Word(english="Receipt", kannada="ಸ್ವೀಕೃತಿ", meaning="Proof of payment", subject="Commerce"),
    Word(english="Stock", kannada="ಸಂಗ್ರಹ", meaning="Stored goods", subject="Commerce"),
    Word(english="Inventory", kannada="ಸಂಗ್ರಹ ಪಟ್ಟಿ", meaning="List of goods", subject="Commerce"),
    Word(english="Wholesale", kannada="ಹೊಲ್ಸೇಲ್", meaning="Bulk selling", subject="Commerce"),
    Word(english="Retail", kannada="ಚಿಲ್ಲರೆ", meaning="Small selling", subject="Commerce"),
    Word(english="Distribution", kannada="ಹಂಚಿಕೆ", meaning="Supply of goods", subject="Commerce"),
    Word(english="Logistics", kannada="ಲಾಜಿಸ್ಟಿಕ್ಸ್", meaning="Transport system", subject="Commerce"),

    Word(english="Entrepreneur", kannada="ಉದ್ಯಮಿ", meaning="Business owner", subject="Commerce"),
    Word(english="Startup", kannada="ಸ್ಟಾರ್ಟ್‌ಅಪ್", meaning="New business", subject="Commerce"),
    Word(english="Management", kannada="ನಿರ್ವಹಣೆ", meaning="Handling business", subject="Commerce"),
    Word(english="Marketing", kannada="ಮಾರ್ಕೆಟಿಂಗ್", meaning="Promoting product", subject="Commerce"),
    Word(english="Advertisement", kannada="ಜಾಹೀರಾತು", meaning="Product promotion", subject="Commerce"),
    Word(english="Brand", kannada="ಬ್ರಾಂಡ್", meaning="Product identity", subject="Commerce"),
    Word(english="Sales", kannada="ಮಾರಾಟ", meaning="Selling goods", subject="Commerce"),
    Word(english="Customer", kannada="ಗ್ರಾಹಕ", meaning="Buyer", subject="Commerce"),
    Word(english="Feedback", kannada="ಅಭಿಪ್ರಾಯ", meaning="Customer response", subject="Commerce"),
    Word(english="Profit margin", kannada="ಲಾಭ ಪ್ರಮಾಣ", meaning="Profit percentage", subject="Commerce")
)